# kubernetes/04a-student-pvc.yaml
# Persistent Volume Claim per workspace studente
# Evita perdita dati al restart del pod
# Applicare per ogni namespace student*

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-workspace-pvc
  namespace: student1  # Sarà sostituito dinamicamente dallo script
  labels:
    app: student-lab
    component: workspace
    student-id: "1"
spec:
  accessModes:
    - ReadWriteOnce  # Accessibile da un solo nodo alla volta
  
  resources:
    requests:
      storage: 5Gi  # Dimensione workspace per studente

  # STORAGECLASS_PLACEHOLDER
  # Questo placeholder sarà sostituito dallo script deploy-lab.sh
  # Se vuoto, usa la StorageClass di default del cluster
