# TLS Configuration per Traefik
# Usa certificato wildcard per tutti gli studenti

---
# ClusterIssuer per Let's Encrypt
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    # HTTP-01 challenge (semplice)
    - http01:
        ingress:
          class: traefik
    
    # DNS-01 challenge per wildcard (richiede DNS provider configurato)
    # Decommenta e configura se usi DNS-01
    # - dns01:
    #     cloudflare:
    #       email: admin@example.com
    #       apiTokenSecretRef:
    #         name: cloudflare-api-token
    #         key: api-token

---
# Certificate wildcard per tutti gli studenti
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-wildcard-cert
  namespace: default
spec:
  secretName: lab-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.lab.example.com"
  dnsNames:
  - "*.lab.example.com"
  - "lab.example.com"

---
# TLS Options per Traefik (security hardening)
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: modern-tls
  namespace: default
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
  # TLS 1.2
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  # TLS 1.3
  - TLS_CHACHA20_POLY1305_SHA256
  - TLS_AES_128_GCM_SHA256
  - TLS_AES_256_GCM_SHA384
  curvePreferences:
  - CurveP521
  - CurveP384
  - X25519
  sniStrict: true
  alpnProtocols:
  - h2
  - http/1.1

---
# TLS Store per certificato default
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: lab-wildcard-tls
  certificates:
  - secretName: lab-wildcard-tls

---
# ServersTransport per backend HTTPS (se necessario)
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: secure-transport
  namespace: default
spec:
  serverName: ""
  insecureSkipVerify: false
  maxIdleConnsPerHost: 100
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 0s
    idleConnTimeout: 90s